[features]
seeds = false
[programs.devnet]
dstage_solana_contracts = "91RwocfXVQjBqryiad78U1hoMJ9Zc7WzjgQAnyWMboae"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/logicon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
